# Generated by Django 4.2.11 on 2024-03-28 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('dob', models.DateField(default=datetime.datetime(2024, 3, 28, 17, 36, 59, 342769))),
                ('department', models.CharField(max_length=30)),
                ('phoneNumber1', models.CharField(max_length=30)),
            ],
        ),
    ]
