# Generated by Django 4.2.11 on 2024-03-29 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_companydetails_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 6, 7, 4, 16293)),
        ),
    ]
