# Generated by Django 4.2.11 on 2024-03-29 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_companydetails_name_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 6, 8, 32, 541305)),
        ),
    ]
