# Generated by Django 4.2.11 on 2024-03-29 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_companydetails_id_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 6, 17, 35, 302535)),
        ),
    ]
